ConsoleCatchall::Console::Reconciliation::Utils::StringHelper
static System.Globalization.CultureInfo ConsoleCatchall.Console.Reconciliation.Utils.StringHelper.Culture()
Referenced by ConsoleCatchall.Console.Reconciliation.Records.CredCard1InOutRecord.Load, ConsoleCatchall.Console.Reconciliation.Records.CredCard2InOutRecord.Load, ConsoleCatchall.Console.Reconciliation.Records.CredCard1Record.Load, ConsoleCatchall.Console.Reconciliation.Records.ActualBankRecord.Load, ConsoleCatchall.Console.Reconciliation.Records.BankRecord.Load.
static string [] ConsoleCatchall.Console.Reconciliation.Utils.StringHelper.Make_sure_there_are_at_least_enough_string_values(int min_values_required, string[] source_array)